[Metadata]

Name = Divine Soul
Author = AvA

Description = Wield divine power with two new Sorcerer kits inspired by the ever so popular 5th Edition Divine Soul.

Readme = https://github.com/DataForInfinity/Sword-Coast-Infinity/blob/main/SCI-Divine-Soul/Readme.txt

Forum = https://www.nexusmods.com/baldursgate/mods/97

Homepage = https://www.nexusmods.com/baldursgate/mods/97

Download = https://github.com/DataForInfinity/Sword-Coast-Infinity

LabelType = GloballyUnique

#Before = NA
#After = IWDification
