[Metadata]

Name = Blades & Bolts
Author = AvA

Description =  Components to enable use of straigth swords for Clerics and Light Crossbows for Clerics and Mages

Readme = https://github.com/DataForInfinity/Sword-Coast-Infinity/blob/main/SCI-Blades+Bolts/Readme.txt

Homepage = https://www.nexusmods.com/baldursgate/mods/91

Download = https://github.com/DataForInfinity/Sword-Coast-Infinity

LabelType = GloballyUnique

#Before = Mods which add new weapons, Mods with Mage or Cleric kits you want to benefit
#After = SCI-Dualadins

